### ISSUE TITLE
Case sensitivity on configuration URL

### ISSUE THREAD

**Issue by MathameticaKen** [MicrosoftDocs/OfficeDocs-SharePoint#3283] opened 2022-05-12 02:14 UTC
The group policy setting for the website URL is Case sensitive - this should be noted.
Entering Contoso.sharepoint.com will not work for contoso.sharepoint.com view in file explorer setting.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by get-itips** [comment] 2022-05-13 17:38
Hello @MathameticaKen how are you?
I tested this on my lab, I configured two SharePoint tenants:

contoso.sharepoint.com -> works

CONTOSO2.sharepoint.com -> also works

I could not reproduce what you experienced, could be that caused by some delay in applying the policy?

**Comment by MathameticaKen** [comment] 2022-05-13 18:06
So I configured this through group policy and waited for the configuration to appear in my edge://policy/ area and on Edge Stable version clicking the Viewinexplorer button it did nothing after multiple attempts so I edited the GPO and waited for the policy to update and the only difference was the Camel casing. It was like ContosoTechnologies.sharepoint.com I will check if I can reproduce again on a AAD and HAADJ device thanks.

**Comment by get-itips** [comment] 2022-05-16 23:15
Hello @MathameticaKen Wondering if you could try again, so far I could not reproduce.

**Comment by get-itips** [comment] 2022-05-23 18:53
@scanum closing as could not reproduce, it can be re-opened in any case.

**Closed by get-itips** 2022-05-23 18:53 UTC
Labels: doc-bug
