### ISSUE TITLE
Link in article to Submit and view feedback for Product is giving error

### ISSUE THREAD

**Issue by virginiablue** [MicrosoftDocs/OfficeDocs-SharePoint#3058] opened 2021-11-23 16:44 UTC
For the article View SharePoint files with File Explorer in Microsoft Edge, Link in article to Submit and view feedback for Product is giving error This UserVoice instance is no longer available. I have a question about Solution that is not working for Classic SharePoint sites using new experience for document libraries. How can I submit this question?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2c3f9bb0-43af-b544-3fd7-71eed410cbec
* Version Independent ID: 250786b4-90f1-0eab-c15d-2f0182d69e5e
* Content: [View SharePoint files with File Explorer in Microsoft Edge - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/SharePoint/sharepoint-view-in-edge)
* Content Source: [SharePoint/SharePointOnline/sharepoint-view-in-edge.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/sharepoint-view-in-edge.md)
* Service: **sharepoint-online**
* GitHub Login: @adeejoseph
* Microsoft Alias: **adjoseph**

**Comment by virginiablue** [comment] 2021-11-23 16:57
After waiting about 45 minutes, the option did appear on classic site document library using new experience. However the link in the article to comment on Product still needs to be fixed.

**Comment by get-itips** [comment] 2021-11-25 16:23
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2925

The link will be changed soon to https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472 you can use that link to share feedback.

Thank you

@scanum please close

**Closed** 2021-11-30 22:25 UTC
Labels: doc-bug
