### ISSUE TITLE
Needs more information

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-SharePoint#3094] opened 2021-12-21 17:46 UTC
In the section for other actions such as renaming, deleting, etc. 

Please add details on how each of these actions impact existing items in lists and libraries that are using the given term. For example, when you rename, it doesn't rename on existing items. This making renaming basically pointless.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38c3945-28eb-8953-4b3f-3d6861434ad3
* Version Independent ID: 110fe1c2-1267-a493-544d-01667fcda8b9
* Content: [Create and manage terms in a term set - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/create-and-manage-terms)
* Content Source: [SharePoint/SharePointOnline/create-and-manage-terms.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/SharePoint/SharePointOnline/create-and-manage-terms.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by get-itips** [comment] 2021-12-23 17:38
Hello @danmyhre Dan, I am looking into this.

**Comment by get-itips** [comment] 2021-12-23 20:11
Dan,
I assigned a term to a document in a DL, then, I renamed the term, it was not right away but a few hours later the new term name was reflected in the item.
Hope this information helps you,

**Comment by danmyhre** [comment] 2022-01-03 13:40
Definitely not seeing this in our environment. And to clarify, I am talking about existing items that are already tagged with the term. We do it updated in the term picker, but not on existing items.

**Comment by get-itips** [comment] 2022-02-17 19:14
Closing as could not reproduce.
Thanks for your feedback!
@scanum

**Closed** 2022-02-17 19:15 UTC
Labels: doc-bug
