### ISSUE TITLE
Restore option is missing

### ISSUE THREAD

**Issue by aaronrwilson** [MicrosoftDocs/OfficeDocs-SharePoint#149] opened 2018-07-29 02:29 UTC
I'm a global admin and the restore option is missing for a delete site.  Why?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d19f5be-8567-336b-cc14-357b20278585
* Version Independent ID: f82afd3a-5e89-fbc2-564a-c49a507de22a
* Content: [View and restore deleted sites in the new SharePoint admin center](https://docs.microsoft.com/en-us/sharepoint/view-and-restore-deleted-sites-in-new-admin-center)
* Content Source: [SharePoint/SharePointOnline/view-and-restore-deleted-sites-in-new-admin-center.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/view-and-restore-deleted-sites-in-new-admin-center.md)
* Service: **sharepoint-online**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by melbamorph** [comment] 2018-08-01 14:07
I am also experiencing the same issue.

![image](https://user-images.githubusercontent.com/3370444/43526621-afda39a4-9572-11e8-9a5e-72e5db4681ac.png)

**Comment by kenwith** [comment] 2018-08-01 17:16
@aaronrwilson and @melbamorph -  thank you for submitting feedback. I am not sure what could be going on and I think the best way forward is if you can open a service ticket in your tenant so this can get resolved ASAP. The support engineers will be able to escalate this right away.

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y

If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by b0cephus** [comment] 2018-08-03 19:17
I have the same issue as well. How about a long term solution?

**Comment by kenwith** [comment] 2018-08-03 19:22
@b0cephus - I was recommending service ticket so that they can escalate and get this resolved. The service engineer will be able to determine if there was a bug in the code or certain environments or problem with doc. I wish there was a way I could help here but I don't have the capabilities that the service engineers have. Would you be open to open a service request too? The support system aggregates these and escalates them to get this resolved for you right away. We can update docs and fix docs based on results too.

Also, looping in @kaarins for information since she owns the article and can update as this gets figured out.

**Comment by kaarins** [comment] 2018-08-03 20:30
Hi @aaronrwilson @melbamorph @b0cephus , thank you for trying the new SharePoint admin center preview and sharing this info with us. The feature team is investigating the issue. If you can provide more info (type of site, whether you are the primary admin for the site, what your admin role is, whether you were the admin who deleted the site), that might help us understand when the button isn't appearing. As you have probably noticed, the button is available only when a single site is selected. The new admin center does not currently support restoring multiple sites at the same time.

If you encounter any other issues or want to make a suggestion, you can send feedback directly to the engineers by clicking the Feedback button in the lower right of the new SharePoint admin center. 

Thank you again,

Kaarin

**Comment by Arcalight** [comment] 2018-08-06 13:02
I have this same issue with restoring a site. It was a site that was automatically created by a group, and I had started using it as a sharepoint testing site. I accidentally deleted the site and tried to restore it from the new sharepoint admin page shown above, but when I selected it, there was no restore option. After some research, I was able to restore it by going in to the exchange admin center and restoring the deleted group. The instructions for this are listed on this page: https://support.office.com/en-us/article/restore-a-deleted-office-365-group-b7c66b59-657a-4e1a-8aa0-8163b1f4eb54. Hopefully this helps, although it would be nice if I could restore from the sharepoint admin center.

**Comment by kaarins** [comment] 2018-08-15 01:06
Thank you, @Arcalight , for this detailed info! The team has been doing a lot of work in this area, and I have tested to confirm that I can restore a group-connected team site when I'm signed in as a global admin. If you don't see this yet, the fix may still be rolling out to your organization. Thanks again for trying out the new admin center preview and helping us identify and fix issues!

**Comment by caspChristian** [comment] 2018-09-20 17:38
@kaarins Is this rolled out to everyone now so that it works?
The reason for asking is that I still see the same as others - no Restore button is available after selecting a Site. - And when using the old UI the sites are not available for restoration at all.

**Comment by MariusJC** [comment] 2018-09-27 14:53
I am also experiencing the same issue. No Restore button is available after selecting a Site.

**Comment by AndreaBarr** [comment] 2018-09-27 16:55
@MariusJC Thank you for this feedback

If you are having issue with this currently we need to get you over to support so we can figure out what is going on. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.

**Comment by caspChristian** [comment] 2018-09-27 17:01
@AndreaBarr And so closing this issue for asking for information - when the issue is not resolved at all?
"What is going on" is quite simple ... **no Restore button is available**
So in the mean time while this is investigated - please update the doc with correct information and pictures. Here is a suggestion for updated text: "You can't do this right now since there is nothing to click on, and our internal communication is in such a state that we are unable to fix it ourselves"
Thanks!

**Comment by AndreaBarr** [comment] 2018-09-27 17:10
@aaronrwilson  It is our process to close the GitHub issue when we send to support or put the issue in the backlog. Support will track the issue and handle it from there. If we put it in the backlog we track it there and comment back when things are fixed or answers are found.

**Comment by caspChristian** [comment] 2018-09-27 17:27
@AndreaBarr And you are not able to respond/tag the correct commenter?

**Comment by francoisvanheerden** [comment] 2018-10-25 06:13
Morning, I have exactly the same issue where the restore option is not available in the Deleted Sites section. I never deleted the site, only the user Group that was automatically created when the site was create, I suspect that this is what caused the site to be deleted. Please can you adivse?

**Comment by HubSaul** [comment] 2018-11-15 11:31
I restored the site using the Restore-SPODeleteSite PowerShell command

This way you don't touch Exchange, and the site immediately moves from Deleted sites to Active Sites.

I just cannot figure out how to determine who deleted the site?

**Comment by tseward** [comment] 2018-11-17 16:16
You can use the audit log in the Office 365 Security & Compliance -> Search & investigation -> Audit log search; under Site administration activities, select Deleted site.

**Comment by kaarins** [comment] 2018-11-26 22:22
The latest update (which has been rolled out to all organizations that have "Targeted release for everyone" selected) allows both global admins and SharePoint admins to restore individual group-connected team sites and all their associated resources. 
Thank you again for trying the new SharePoint admin center and sending your feedback. To share other suggestions or report bugs, please click the Feedback button in the lower right of the admin center.

**Closed by kaarins** 2018-11-26 22:22 UTC
Labels: SharePoint Online
