### ISSUE TITLE
Configure team site libraries to sync automatically

### ISSUE THREAD

**Issue by schenardie** [MicrosoftDocs/OfficeDocs-SharePoint#1349] opened 2019-09-18 03:15 UTC
To find the library ID, sign in as a global or SharePoint admin in Office 365, browse to the library, and click the Sync button. In the "Starting sync" dialog box, click the Copy library ID link.

the Copy library ID link is no longer available once the Sync button is clicked. Currently there are no other documented methods of getting the library ID.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04ad2f16-c861-7a1b-5c1d-e4601e8f3855
* Version Independent ID: c47df4cd-f706-d807-5eac-172fba1e500f
* Content: [Use Group Policy to control OneDrive sync client settings](https://docs.microsoft.com/en-us/onedrive/use-group-policy#BlockExternalSync)
* Content Source: [OneDrive/use-group-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/use-group-policy.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by tseward** [comment] 2019-09-18 15:26
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1326.

**Comment by scanum** [comment] 2019-09-19 04:02
@schenardie Closing because it is a duplicate

**Comment by pjsyeah** [comment] 2019-09-19 17:57
@scanum, Is it safe to say, then, that 'Copy Library Link ID' will return?

**Comment by dplotnikov** [comment] 2019-09-24 21:32
@pjsyeah Microsoft doesn't have any information about this

**Comment by dplotnikov** [comment] 2019-09-24 21:32
@scanum feel free to close this as a duplicate

**Comment by erikhoenderdos** [comment] 2019-09-26 12:31
Hi,

The Solution suggested doesn't work for me. We want to syn only the files from the General Channel in teams. not from al the other channels. Before i could get the ID from any folder using the Sharepoint COPY LINK button. Now i cannot find the FOLDER ID of the general folder.

Does anyone know how to add the FOLDER ID to the URL. 

`Connect-PnPOnline https://tenantName.sharepoint.com/sites/siteName
Get-PnPSite -Includes Id | Select Id
Get-PnPWeb | Select Id
Get-PnPList 'Documents' | Select Id`

The folder id is just before the web id in the whole string..

I need this part added in the string: 
FIRST_PART_OF_TENANTID_STRING.......folderId=c3f9ec38%2De2b5%2D4c45%2D8340%2Dbff6d6c62fdf&webUrl=htt.....LAST_PART_OF_TENANTID_STRING

**Comment by dplotnikov** [comment] 2019-09-26 15:58
@erikamenezes this article doesnt' cover your scenario at all

**Comment by win2000b** [comment] 2019-09-27 11:38
If this copy library ID feature is not going to be shown going forward can we get the documentation amended to reflect this. Otherwise people are going to look for it and log more cases.

**Comment by dplotnikov** [comment] 2019-09-27 20:31
@win2000b I've just made a test and I see it even after I've configured sync. Did I miss something?

**Comment by win2000b** [comment] 2019-09-27 20:33
The link to copy library does not appear in the gui all the time. Seems hit and miss. Other users are reporting the same. In previous cases. Like 1326 they said it’s being removed from the gui.

**Comment by dplotnikov** [comment] 2019-09-27 20:39
Right, but what I'm saying it's okay on my end but I'm on a Mac. I would suggest updating the article with a Note like "Sometimes Copy Library ID button could be unavailable in case if a given library was already synced via the OneDrive client."

What do you think @win2000b ?

**Comment by tseward** [comment] 2019-09-28 15:19
@dplotnikov the issue is the dialog was changed as part of a product update and no longer matches the previous dialog shown. I've submitted a PR to provide the instructions via PowerShell while the PG determines how to re-approach this.

**Comment by scanum** [comment] 2019-09-30 04:18
@schenardie Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2019-09-30 04:18 UTC
