### ISSUE TITLE
Set-SPOTenant -SyncAadB2BManagementPolicy $True

### ISSUE THREAD

**Issue by brassman2000** [MicrosoftDocs/OfficeDocs-SharePoint#1132] opened 2019-07-01 19:16 UTC
Our Office365 Tenant used for testing has the AAD B2B private preview and we are looking to enable  integration with SharePoint/OneDrive.

After calling Set-SPOTenant -SyncAadB2BManagementPolicy $True, a subsequent call to validate the change via Get-SPOTenant shows that SyncAadB2BManagementPolicy  is still $False.

Is this an issue with the API or our Tenant?

**Comment by MikePlumleyMSFT** [comment] 2019-07-02 13:56
Duplicate of [issue 1133](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1133).

**Closed by MikePlumleyMSFT** 2019-07-02 13:56 UTC
