### ISSUE TITLE
The meaning of the note is the opposite in the Japanese article.

### ISSUE THREAD

**Issue by kefujino** [MicrosoftDocs/OfficeDocs-SharePoint#2631] opened 2021-03-11 01:52 UTC
This feedback is for translation bug in the Japanese article.

https://docs.microsoft.com/ja-jp/onedrive/restore-deleted-onedrive

![image](https://user-images.githubusercontent.com/13634805/110723538-91835100-8257-11eb-8ca4-1c8e95c21ced.png)

Original
>When you permanently delete a OneDrive, you will not be able to restore it.

Current
>OneDrive を完全に削除すると、その OneDrive を復元できます。

My suggestion

>OneDrive を完全に削除すると、**その OneDrive は復元できません。**
---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3384358-57c3-7117-f4c4-5da891cbf2fd
* Version Independent ID: e253e442-722d-acc7-1155-ee90ed1c324f
* Content: [Restore a deleted OneDrive - OneDrive](https://docs.microsoft.com/en-us/onedrive/restore-deleted-onedrive?source=docs)
* Content Source: [OneDrive/restore-deleted-onedrive.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/OneDrive/restore-deleted-onedrive.md)
* Service: **one-drive**
* GitHub Login: @kaarins
* Microsoft Alias: **kaarins**

**Comment by scanum** [comment] 2021-03-16 06:20
@kefujino Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@OfficeGlobal Could you kindly help with this issue? Thanks!

**Comment by TinaMcN** [comment] 2021-04-03 01:46
@kefujino thanks for reporting the issue.  It is a bug with the machine translation.  I sent the article to be human translated and it should be completed in approx 3-4 days.

**Comment by TinaMcN** [comment] 2021-04-05 23:24
@kefujino the article is now human translated.  Can you please check if the issue is fixed now and close if it looks ok?  Thanks again for letting us know about the issue.

**Comment by scanum** [comment] 2021-05-03 04:16
Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2021-05-03 04:16 UTC
