### ISSUE TITLE
Recommend updating the "classic workflow" note on this page

### ISSUE THREAD

**Issue by joshtransient** [MicrosoftDocs/OfficeDocs-SharePoint#2318] opened 2020-09-11 19:31 UTC
Says it's supported until 2026, definitely no longer true...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f76ff1b8-cf92-2014-8847-35ff8befd854
* Version Independent ID: cb83aa55-6973-c3e7-f58e-ff6f8df45320
* Content: [SharePoint Server Team Sites Migration Guide - Migrate to SharePoint and OneDrive](https://docs.microsoft.com/en-us/sharepointmigration/sp-teams-sites-migration-guide)
* Content Source: [migration/sp-teams-sites-migration-guide.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/sp-teams-sites-migration-guide.md)
* Service: **sharepoint-online**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment] 2020-09-14 05:18
@joshtransient Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment] 2020-09-24 17:59
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/2269
There is already a PR on this will link here.
Thanks!

**Closed** 2020-10-22 13:53 UTC
