### ISSUE TITLE
Notes for importing via csv to Microsoft Teams

### ISSUE THREAD

**Issue by TeamTerry** [MicrosoftDocs/OfficeDocs-SharePoint#392] opened 2018-11-10 23:04 UTC
There are a few gotchas with importing to Teams, specifically the csv file columns E and F.
If you do not populate column F with the word General, and just use column E with the word Documents, the files will not appear in Microsoft Teams.
They will successfully upload into the SharePoint Online site.

If you want to import files to the Teams Files location, you have to have the csv file as below, in particular columns E and F

Column A - your file location - c:\USB\Files to Import
Column B - empty for file import from USB
Column C - empty for file import from USB
Column D - The URL of the SPO site - Shorten to just show the site name - https://tenant.sharepoint.com/sites/SiteName
Column E - Use the word - Documents
Column F - Use the word - General

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27475eb6-82f5-1f75-a304-e5696092a3e1
* Version Independent ID: e9bd89b2-a04d-5509-5c76-fc0602cc8515
* Content: [How to format your CSV or JSon file for data content migration](https://docs.microsoft.com/en-us/sharepointmigration/how-to-format-your-csv-file-for-data-content-migration)
* Content Source: [migration/how-to-format-your-csv-file-for-data-content-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/migration/how-to-format-your-csv-file-for-data-content-migration.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by AndreaBarr** [comment] 2018-11-13 19:12
@TeamTerry Thank you for this updated

I will get this csv information over to the SharePoint team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by tseward** [comment] 2018-11-17 16:02
@TeamTerry This would be 'by design' I suppose. The SPMT doesn't import data to Teams, Teams just displays content of the 'Documents' library with the channel name being a subfolder (General, being the default channel).

You can always add a new tab to the channel and point it at the desired SharePoint location.

**Comment by DaanvanBeek** [comment] 2019-01-10 08:17
@tseward Bit late to the party but I wanted to chip in there:
Adding a new tab to the channel and pointing it at the desired SharePoint location is not good in most cases in my experience, as Teams presents the (non-removable) tab that is located at %site%/Documents/%tab% as "the way to access your data".

**Comment by tseward** [comment] 2019-01-10 16:01
Agreed it isn't as streamlined as using the Documents library, but it is a supported scenario and one that you will often see with those who already have some form of SharePoint presence.

**Comment by tseward** [comment] 2019-02-02 19:35
@scanum I think we can close this one as there is nothing to "fix" in the article.

**Closed** 2019-02-04 17:44 UTC
Labels: Migration

**Comment by bjdyke** [comment] 2019-03-08 14:46
@TeamTerry I can also add that for those of us not working in English, you need to specify the local language equivalent in Column E, so in my case in Sweden/Swedish, Dokument. Strangely enough General is to be retained in the English in Column F. Does anyone know if you can specify a 3rd subfolder?

**Comment by D3w4yne** [comment] 2020-04-13 23:42
You used to be able to specify a sub folder of a channel by using "General/Subfolder" syntax but now (doing a migration tonight) I find that it's not working...

**Comment by AdamJB19** [comment] 2020-04-20 07:35
Is there a resolution for this? I also want to be able to provide subfolder mapping under General in the CSV format
