### ISSUE TITLE
https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2019#sharepoint-home-page

### ISSUE THREAD

**Issue by mikelee-msft** [MicrosoftDocs/OfficeDocs-SharePoint#291] opened 2018-10-02 17:57 UTC
This section https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2019#sharepoint-home-page  needs to be updated:

Current:
You can reach the SharePoint home page by clicking on the "Sites" icon in the SharePoint app launcher. The SharePoint home page replaces the old sites.aspx experience.

Suggested:
You can reach the SharePoint home page by clicking on the "SharePoint" icon in the SharePoint app launcher. The SharePoint home page replaces the old sites.aspx experience.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f0c473c-9953-3f98-5ba5-7fda35879614
* Version Independent ID: 79194e89-ce43-eefc-6439-cf2bd5bdac57
* Content: [New and improved features in SharePoint Server 2019 Public Preview](https://docs.microsoft.com/en-us/sharepoint/what-s-new/new-and-improved-features-in-sharepoint-server-2019#sharepoint-home-page)
* Content Source: [SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-SharePoint-Server-2019.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/what-s-new/new-and-improved-features-in-SharePoint-Server-2019.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by AndreaBarr** [comment] 2018-10-03 19:16
@mikelee-msft Thank you for this feedback

We appricate you helping us make sure the docs stay updated. It looks like Trevor has updated the article to reflect your suggestion. I am going to close this issue as resolved. If the issue is not resolved please reopen the issue.

**Closed by AndreaBarr** 2018-10-03 19:16 UTC
