### ISSUE TITLE
error code 0x0131000D is missing in table "SPMT error codes"

### ISSUE THREAD

**Issue by AndreSchiemann** [MicrosoftDocs/OfficeDocs-SharePoint#3557] opened 2022-12-12 09:32 UTC
In the table "SPMT error codes" is following error code not listed: **0x0131000D**

Please add this error code and help how to handle the root cause.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cfa08336-690e-0d21-6491-3f14f6d13391
* Version Independent ID: 8927975a-7956-fc72-055e-36603e4eddaf
* Content: [Troubleshoot SharePoint Migration Tool - Migrate to Microsoft 365](https://learn.microsoft.com/en-us/sharepointmigration/troubleshooting-common-spmt-issues)
* Content Source: [migration/troubleshooting-common-spmt-issues.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/public/migration/troubleshooting-common-spmt-issues.md)
* Service: **sharepoint-online**
* Sub-service: **sharepoint-migration**
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by get-itips** [comment] 2023-01-05 20:01
Looking into this

**Comment by JoanneHendrickson** [comment] 2023-01-05 21:04
Contacting PM as to root cause.

**Comment by get-itips** [comment] 2023-03-07 16:51
@JoanneHendrickson any news from PM? Thank you :)

**Comment by scanum** [comment] 2023-10-02 04:56
@JoanneHendrickson any news from PM? Thank you :)

**Comment by JoanneHendrickson** [comment] 2023-11-03 14:50
Per the PM this error is no longer an issue in the current versions of SPMT.  Closed as resolved.

**Closed by JoanneHendrickson** 2023-11-03 14:50 UTC
Labels: doc-bug, writer-input-required
