### ISSUE TITLE
This, for somebody who barely understands federation will be impossible to even follow.

### ISSUE THREAD

**Issue by vitaprimo** [MicrosoftDocs/OfficeDocs-SharePoint#1785] opened 2020-02-24 01:16 UTC
A lot of these articles are repeating some form of an incomplete message over and over while overlapping here and there.

It's beyond me how Microsoft feels it's OK to charge 7G for a product with an almost 10-year old, patched up documentation. This SAML method is explained several other times in the articles on the sidebar, each is inconsistent, vague, with tons of links outside of the articles. But it's more astonishing why on earth they can't decide on a single certificate store and pick a random attribute each time to represent it. Finish a product already! I mean… The UI of most of the server stuff is MMC, which is from like 2000. People pay Microsoft for the UI, not because of reliability, security, confidence, trust, savings or efficiency of all of their server products. For the seven grand sticker price of SharePoint (+predatory reselling) is it too much to ask for nice UI--you make both SharePoint and ADFS for goodness' sake, ADFS is also with a high entrance free BTW.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4559926-c6e8-03b7-f07c-20adc26c14d6
* Version Independent ID: 7094c31c-64de-5504-d1a4-500478309181
* Content: [Implement SAML based authentication in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server#feedback)
* Content Source: [SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/security-for-sharepoint-server/implement-saml-based-authentication-in-sharepoint-server.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment] 2020-02-24 06:04
@vitaprimo Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by vitaprimo** [comment] 2020-02-29 00:35
I really hope you do because it's been a frustrating experience so far, SharePoint was supposed to be a something that would be a helpful tool.

It lot needs to be clarified, for instance, setting ADFS with SharePoint don't sets up the correct relationship with the data in the directory, even though both SharePoint and ADFS use the directory as the userbase. Things such as extending the web application and/or installing third party tools such as LDAPCP (which half of the time installs but it's not registered as a Claims Provider) are still necessary.

It's best practice to put the My Sites host into its own web application; if using ADFS that would need to have its own identifier. But it's not mentioned anywhere how to add a second SAML provider that will use the same certificate. Trying to add another will result in an error saying it's already been added.

A lot needs change, and just sending small users who are able to get SharePoint but cannot afford an ongoing IT department to Office365 is not a solution. A finished product should not have this many errors and gotchas. A finished product should not need PowerShell scripting at all.

**Comment by scanum** [comment] 2020-05-06 04:27
@vitaprimo We understand your frustration, we are actively working on getting this worked on. Thanks for your patience.

**Comment by tseward** [comment] 2020-08-01 23:34
@vitaprimo SAML configurations (Service Providers, like SharePoint in this case) do not have access to the directory data, unlike the IdP (AD FS in your case, likely with Active Directory). SAML passes _attributes* to the service provider (SharePoint) and no additional information. The behavior you're seeing, without 3rd party solutions like LDACP, is by design of the authorization protocol. But the impact you're seeing of SAML on SharePoint is one reason I do not recommend it to anyone who asks -- there are generally few reasons to implement it.

While you're right, you can't add a duplicate *certificate*, you can reuse the previously installed certificate.

As you've likely seen, Microsoft service and server software has been moving to PowerShell configurations as the primary configuration vehicle, with a UI _sometimes_ implemented for that same configuration -- but more often than not, no UI is.

We can't address product deficiencies or features in this repository as this repository is for improving the documentation, but if you do have product feedback, you can add it at https://sharepoint.uservoice.com.

My take away from this is the article needs the following improvements:

* Overall polish -- the article is difficult to read and not laid out very well
* Adding additional web applications using SAML auth
* Explanation of the UX that admins and users experience with a SAML configuration (i.e. people picker resolution doesn't function)

Please let me know if I've missed anything.

**Comment by scanum** [comment] 2020-08-05 03:56
@vitaprimo Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Closed by scanum** 2020-08-05 03:56 UTC
