### ISSUE TITLE
Site Policy with SharePoint Online

### ISSUE THREAD

**Issue by ravick4u** [MicrosoftDocs/OfficeDocs-SharePoint#1482] opened 2019-10-31 12:24 UTC
I can see this document is not valid for SharePoint Online but this feature is still available in SharePoint Online. Could you please let me know what's Microsoft's direction on using this feature in SharePoint Online

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 05df8f37-499e-26ad-a44c-db33cbc3f71f
* Version Independent ID: 6952b838-2857-91d2-28a7-9dff9a042a64
* Content: [Overview of site policies in SharePoint Server](https://docs.microsoft.com/en-us/sharepoint/sites/site-policy-overview)
* Content Source: [SharePoint/SharePointServer/sites/site-policy-overview.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/sites/site-policy-overview.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment] 2019-10-31 21:26
@ravick4u Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment] 2020-01-03 20:55
Duplicate of https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/issues/1481

**Comment by scanum** [comment] 2020-02-26 19:04
@ravick4u

**Closed by scanum** 2020-02-26 19:04 UTC
