### ISSUE TITLE
This page contains impossible instruction

### ISSUE THREAD

**Issue by Ofer-Gal** [MicrosoftDocs/OfficeDocs-SharePoint#2530] opened 2021-01-08 14:09 UTC
The page has a statement: 

>Depending on the search scenario, some Microsoft Search features might not work if the classic global Search Center URL is not set to "yourcompanyname.sharepoint.com/search/pages". Ensure that the Search Center site collection exists, that its URL is set to "yourcompanyname.sharepoint.com/search/pages", and that all users have read access to it.

Site collections can only be created under /sits/ or /teams/ SPO does not have the option of custom managed path.
When trying to create a subsite "yourcompanyname.sharepoint.com/search" you get an error:

> "search" cannot be used as a site name. Site names cannot contain certain reserved words and cannot begin with an underscore. Please enter a different name.

please provide accurate instructions for a search center
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e29f89b7-afd4-1b65-f3ad-c802c7dd5a47
* Version Independent ID: 0f3e61c4-6b03-dccb-6067-09ed98228f62
* Content: [Difference between classic & modern search experiences - SharePoint - SharePoint in Microsoft 365](https://docs.microsoft.com/en-us/sharepoint/differences-classic-modern-search)
* Content Source: [SharePoint/SharePointOnline/differences-classic-modern-search.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointOnline/differences-classic-modern-search.md)
* Service: **sharepoint-online**
* GitHub Login: @MikePlumleyMSFT
* Microsoft Alias: **mikeplum**

**Comment by scanum** [comment] 2021-01-12 03:11
@Ofer-Gal Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment] 2021-01-13 12:29
Hello @Ofer-Gal how are you? Hope you are doing good.

I could dig more into this, and the /search/pages path was intended for old tenants, on new tenants, this location is https://tenant.sharepoint.com/search (that path is already present for you when the SPO tenant is set up)

Will propose some improvements to the article. Thank you

**Comment by Ofer-Gal** [comment] 2021-01-13 16:37
So I do not need my own Search center? https://ecgmcaz.sharepoint.com/search is the search center for tenant ecgmcaz?

**Comment by get-itips** [comment] 2021-01-13 17:53
@Ofer-Gal You can find more information about Search in SPO [here](https://docs.microsoft.com/en-us/sharepoint/manage-search-center).

**Comment by get-itips** [comment] 2021-01-25 20:40
@scanum Please kindly close this issue.

**Closed** 2021-01-26 12:44 UTC
