### ISSUE TITLE
Sharepoint 2019 and 2016 with sql 2017

### ISSUE THREAD

**Issue by adalfa** [MicrosoftDocs/OfficeDocs-SharePoint#863] opened 2019-04-03 13:58 UTC
On the component list for RBS provider there is no note about sharepoint 2019 nor any feature pack for the RBS client that apply to sql 2017

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c4bfb2a-e225-fad9-5970-ca30acf9d92d
* Version Independent ID: 7cc3baec-8c7e-e5ee-cf16-812a4aa3c035
* Content: [Install and configure RBS with FILESTREAM in a SharePoint Server farm](https://docs.microsoft.com/en-us/sharepoint/administration/install-and-configure-rbs)
* Content Source: [SharePoint/SharePointServer/administration/install-and-configure-rbs.md](https://github.com/MicrosoftDocs/OfficeDocs-SharePoint/blob/live/SharePoint/SharePointServer/administration/install-and-configure-rbs.md)
* Product: **sharepoint-server-itpro**
* GitHub Login: @bentoncity
* Microsoft Alias: **stevhord**

**Comment by tseward** [comment] 2019-04-03 14:43
Question is, why would you even want to use RBS with a version of SharePoint that only supports SQL Standard/Enterprise? :-)

@AndreaBarr assign to me, please.

**Comment by jpalo** [comment] 2019-04-16 13:09
How should we proceed in the following scenarios, are they even supported?
- SP2016+SQL2017
- SP2019+SQL2016
- SP2019+SQL2017

**Comment by tseward** [comment] 2019-04-16 14:53
RBS is supported, but you shouldn't use it. Trying to dig up some info on this and will get back to it as soon as possible.

**Comment by jpalo** [comment] 2019-04-16 15:43
Thanks, I'd appreciate some insight regarding the "shouldn't use it" part. Is the suggestion to store GB sized files in DB?

**Comment by tseward** [comment] 2019-04-16 15:47
RBS was designed for those coming from SQL Express where there was (originally) a 4GB MDF limit. RBS introduces unnecessary complexity into the environment, primarily related to backup/restores/high availability. It also caps you at a hard 200GB database size limit (including RBS content) where as SharePoint storing docs in SQL supports 4TB+ databases. It is not designed to improve performance.

As for storing GB-sized files, that would obviously be a question of what they are/what you're using them for and is SharePoint an appropriate storage location at all. For example, I wouldn't store ISOs in SharePoint because it doesn't serve a good purpose to do so.

**Comment by jpalo** [comment] 2019-04-16 16:05
Others say RBS cap at 200GB is soft limit, like the generic 200GB DB soft limit we've had forever. https://sharepoint.stackexchange.com/questions/138804/why-200gb-content-db-limit-when-using-rbs

**Comment by tseward** [comment] 2019-04-16 16:09
https://docs.microsoft.com/en-us/SharePoint/install/software-boundaries-and-limits-0

> If you are using Remote BLOB Storage (RBS), the total volume of remote BLOB storage and metadata in the content database **must not** exceed the 200GB limit. 

"Must not" means hard limit.

**Comment by scanum** [comment] 2019-05-07 00:07
@adalfa Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment] 2019-05-07 00:07
@officedocsbot close

**Closed by scanum** 2019-05-07 00:07 UTC
